#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'quickSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def quickSort(arr):
    # Write your code here

    # Initialize two empty lists to store elements smaller than and greater than the first element of the input list 'arr'.
    left, right = [], []

    # Iterate through the elements of the input list 'arr' starting from the second element (index 1).
    for i in range(1, len(arr)):

        # Check if the first element (at index 0) is greater than the current element at index 'i'.
        if arr[0] > arr[i]:

            # If the condition is true, add the current element to the 'left' list.
            left.append(arr[i])
        else:

            # If the condition is false, add the current element to the 'right' list.
            right.append(arr[i])

    # After processing all elements, add the first element (at index 0) to the 'left' list.
    left.append(arr[0])

    # Concatenate the 'left' and 'right' lists to form a single list.
    # The 'left' list contains elements smaller than the first element, and the 'right' list contains elements greater than or equal to the first element.
    # The resulting list is the sorted version of the input list 'arr'.
    return left + right

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = quickSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
