#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countSort' function below.
#
# The function accepts 2D_STRING_ARRAY arr as parameter.
#

def countSort(arr):
    # Write your code here

    # Create a list called idxArr containing 100 empty lists.
    idxArr = [[] for i in range(100)]

    # Iterate through the 'arr' list using a for loop.
    for i in range(len(arr)):

        # Extract the integer value from the first element of the current 'arr' element.
        idx = int(arr[i][0])

        # Check if the current index 'i' is less than half the length of the 'arr' list.
        if i < len(arr) / 2:

            # If 'i' is less than half, append a "-" to the 'idxArr' list at index 'idx'.
            idxArr[idx].append("-")
        else:

            # If 'i' is greater than or equal to half, append the second element of the current 'arr' element to 'idxArr' at index 'idx'.
            idxArr[idx].append(arr[i][1])

    # Convert the 'idxArr' list into a string, joining all the elements with spaces.
    # Then, remove leading and trailing spaces using lstrip() and rstrip() methods.
    # Finally, print the resulting string.
    print(" ".join(map(lambda r: " ".join(r), idxArr)).lstrip().rstrip())

if __name__ == '__main__':
    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(input().rstrip().split())

    countSort(arr)
